In [3]:
import numpy as np

# ND array

### 1.1 Create ndarray

In [4]:
l = [1,2,3,4]
arr2 = np.array([l, l])  
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


In [6]:
eye_arr = np.eye(4) 
print(eye_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
z_arr = 0 * eye_arr
print("Method 1.")
print(z_arr)
z_arr = np.zeros(4)
print("Method 2.")
print(z_arr)

Method 1.
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Method 2.
[0. 0. 0. 0.]


In [8]:
z_arr = np.zeros(shape = (4, 6))
print(z_arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
arr1 = np.ones(4)
print("{} \n".format(arr1))
arr1 = np.ones(shape = (4, 6)) 
print(arr1)

[1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
parti = np.linspace(0, 10, 2)     # 0 and 10 range and 2 as partition
print(parti)

[ 0. 10.]


In [17]:
rarr = np.random.rand(2, 3)     # 2 rows 3 columns
print(rarr) 

[[0.13268895 0.3792458  0.97723074]
 [0.43176198 0.89940174 0.26901725]]


In [18]:
rarr = np.random.rand(2, 2, 6)    # 2- 2 times, 2 - rows each time, 6 - columns each time
print(rarr)

[[[0.93359548 0.30174476 0.93293087 0.05146246 0.82322527 0.61231597]
  [0.21993802 0.83803218 0.9477284  0.84694259 0.79870992 0.14869881]]

 [[0.81632957 0.61737176 0.41048832 0.70148034 0.70072815 0.58934062]
  [0.47876072 0.6060743  0.17325708 0.73837366 0.65287991 0.46022502]]]


In [19]:
rarr = np.random.randn(2,3)  # 2 rows 3 columns
print(rarr)

[[-3.31376074 -0.53465566  0.14827223]
 [-1.64165757 -0.50196518 -2.57853175]]


In [20]:
n = np.random.randint(10, 20)
print(n)

15


### 1.2 Functions / Features

In [21]:
l = [1,2,3,4]
arr2 = np.array([l, l])  
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


In [22]:
print(type(arr2))

<class 'numpy.ndarray'>


In [24]:
print(arr2.size)

8


In [25]:
print(arr2.shape)

(2, 4)


In [26]:
rarr = np.random.randn(2,3)
print(rarr)
rarr = rarr.reshape(3,2)
print(rarr)

[[ 0.66636048 -0.02533113 -1.40643754]
 [ 0.2326001  -0.43359651  1.64041996]]
[[ 0.66636048 -0.02533113]
 [-1.40643754  0.2326001 ]
 [-0.43359651  1.64041996]]


In [27]:
arr = np.arange(50,70)
arr_tf = arr > 55   
print(arr_tf)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [28]:
arr = np.arange(50,70)
arr_tf = arr > 55            # bool type array
print(sum(arr_tf))           # Count true value

14


In [29]:
arr = np.arange(50,70)
arr_tf = arr + 100            # Add number to every element of array
print(arr_tf)

[150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169]


In [30]:
mat = np.random.rand(5,5)
print(mat)
print(np.cos(mat))

[[0.55991644 0.27478449 0.96966904 0.40539089 0.75953401]
 [0.29300584 0.10977476 0.81377368 0.33681009 0.10271154]
 [0.40730825 0.49687608 0.3347278  0.87544788 0.21004177]
 [0.17118842 0.06901389 0.46413687 0.32260211 0.76318928]
 [0.61312786 0.78820527 0.09340112 0.75037634 0.67852645]]
[[0.84729949 0.9624837  0.56557251 0.91894831 0.72515696]
 [0.95738002 0.9939808  0.6867603  0.94381366 0.99472981]
 [0.91819046 0.87907597 0.94449977 0.64065303 0.97802221]
 [0.98538301 0.99761949 0.89420828 0.94841367 0.72263516]
 [0.81785216 0.70511907 0.99564129 0.73143229 0.77849844]]


In [31]:
arr = np.arange(50,70)
print(arr)
print(np.mean(arr))

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
59.5


In [32]:
arr1 = np.random.random(size = (3,3))
arr2 = np.random.random(size = (3,3))
print(arr1)
print(arr2)

# Put array 2 on right side of arr1 - Horizontal stacking - rows of both matrix should be same.
n_arr = np.hstack((arr1, arr2))
print(n_arr)

# Put array 2 on below of array 1 - Vertical stacking - columns of both matrix should be same.
n1_arr = np.vstack((arr1, arr2))
print(n1_arr)

[[0.88103263 0.80877332 0.51056573]
 [0.32435539 0.873825   0.74331112]
 [0.49411396 0.13230176 0.70306683]]
[[0.4606678  0.66653312 0.19548971]
 [0.54871942 0.41168687 0.94390574]
 [0.88760677 0.6787935  0.68182272]]
[[0.88103263 0.80877332 0.51056573 0.4606678  0.66653312 0.19548971]
 [0.32435539 0.873825   0.74331112 0.54871942 0.41168687 0.94390574]
 [0.49411396 0.13230176 0.70306683 0.88760677 0.6787935  0.68182272]]
[[0.88103263 0.80877332 0.51056573]
 [0.32435539 0.873825   0.74331112]
 [0.49411396 0.13230176 0.70306683]
 [0.4606678  0.66653312 0.19548971]
 [0.54871942 0.41168687 0.94390574]
 [0.88760677 0.6787935  0.68182272]]


In [33]:
arr1 = np.random.random(size = (3,3))
arr2 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr2 = arr2 * 10
print(arr1)
print(arr2)
# Floor
print(np.floor(arr1))
print(np.ceil(arr2))

[[0.37325168 2.88190338 2.36440597]
 [4.82453891 0.82538462 6.82156315]
 [8.33901387 2.9853793  9.70761134]]
[[7.15661389 8.0063262  0.30620694]
 [0.47458588 7.35289901 9.79167362]
 [1.38347172 6.59701355 9.51156509]]
[[0. 2. 2.]
 [4. 0. 6.]
 [8. 2. 9.]]
[[ 8.  9.  1.]
 [ 1.  8. 10.]
 [ 2.  7. 10.]]


In [34]:
import numpy as np
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.sum(arr1))

56.81123250957403


In [35]:
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.sum(arr1, axis = 0))

[ 4.53850763 15.38624639 17.075666  ]


In [42]:
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.sum(arr1, axis = 1))

[15.22931903 10.97524637 16.53597842]


In [37]:
# This axis =0 or 1 work with most of other functions too
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.mean(arr1, axis = 0))

[6.73397758 3.79774705 4.22191203]


In [38]:
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.mean(arr1, axis = 1))

[5.14536363 5.79923475 6.27114023]


In [39]:
# Cummulative sum
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.cumsum(arr1))

[ 1.1752092   4.96005173 10.60865516 17.96664165 21.01785642 28.08961494
 31.30769453 39.05679667 44.83065657]


In [40]:
# Cummulative product
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
print(np.cumproduct(arr1))

[9.32848717e+00 6.73320661e+01 2.60433334e+01 1.36239249e+02
 3.64220042e+02 3.26300233e+03 5.30658449e+03 3.91954465e+04
 5.79615417e+04]


In [41]:
# unique values
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr1 = np.floor(arr1)
print(np.unique(arr1))

[0. 1. 2. 3. 4. 5. 8. 9.]


In [43]:
# Min 
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr1 = np.floor(arr1)
n = np.min(arr1)
print(arr1)
print(n)

[[2. 7. 4.]
 [1. 2. 9.]
 [9. 8. 0.]]
0.0


In [44]:
# Max
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr1 = np.floor(arr1)
n = np.max(arr1)
print(arr1)
print(n)

[[7. 6. 1.]
 [2. 3. 2.]
 [1. 6. 7.]]
7.0


In [45]:
# Max as columns
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr1 = np.floor(arr1)
n = np.max(arr1, axis = 0)
print(arr1)
print(n)

[[1. 3. 5.]
 [0. 4. 0.]
 [9. 2. 2.]]
[9. 4. 5.]


In [46]:
# Max as rowwise
# 0 is for column
# 1 is for rows in term of axis =
arr1 = np.random.random(size = (3,3))
arr1 = arr1 * 10
arr1 = np.floor(arr1)
n = np.max(arr1, axis = 1)
print(arr1)
print(n)

[[4. 9. 4.]
 [5. 9. 3.]
 [7. 1. 0.]]
[9. 9. 7.]


In [47]:
# Enumerate through vector
arr = np.arange(1, 10)
for item in arr:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
arr = np.arange(12, 30)
for idx,item in enumerate(arr):    # Starts with zero
    print(idx,item)

0 12
1 13
2 14
3 15
4 16
5 17
6 18
7 19
8 20
9 21
10 22
11 23
12 24
13 25
14 26
15 27
16 28
17 29


In [49]:
## Linear algebra with Numpy
mat = np.array([[1,2], [3,4]])
print(mat)

[[1 2]
 [3 4]]


In [50]:
# Find the determinant 
print(np.linalg.det(mat))

-2.0000000000000004


In [51]:
# Find the inverse
print(np.linalg.inv(mat))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
# Find the transpose
print(np.transpose(mat))

[[1 3]
 [2 4]]


In [53]:
# Diagonal addition
print(np.trace(mat))

5


In [54]:
# Matrix multiplication
# Element by element multiplication
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(arr1 * arr2)
# same goes to other arithmatic operation

[[ 1  4]
 [ 9 16]]


In [55]:
# True real multiplication
print(arr1.dot(arr2))

[[ 7 10]
 [15 22]]


In [56]:
# Solve equation
#2x + y = 1
#x + y = 2

m = np.array([[2,1], [1,1]])
n = np.array([1,2])

print(np.linalg.solve(m,n))

[-1.  3.]


In [57]:
#ign value and ign vector
# Eigen vector and Eigen value are use to reduce noise in data. They also help to improve
# efficiency of computataionally.
# Eigen vectors makes understanding of linear transformation easy.
# EE have their importance in linear differential equation.
# We can find rate of change
# We can maintain relationship between two variables
# one eigenvalue and eigenvector are used to capture key information that is stored in a large matrix.
# Equation
# A * x = lambda * x
# Where A is matrix and x is Evector and lambda is Evalue
# Find the EValue
# Determinant(A - lambda * I) = 0
arr1 = np.array([[1,2],[3,4]])
rigvalue, eigvector = np.linalg.eig(arr1)
print(rigvalue)
print(eigvector)
# But what is eigen vector ana its actual use still now sure

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [58]:
# List and Numpy array
a = [1, 4, 4.5, 'String', True]
print(a)
# List accept any type of element
arr = np.array(a)
print(arr)
# Numpy accept homogeneous array as a element type
# We can perform same operaations on each element of array because they are of same type.
# But this is not true in case on list

# When we create numpy array it occupies fix amount of memory but in case of list it is
# dynamic in nature

# Performance wise numpy array is fast

[1, 4, 4.5, 'String', True]
['1' '4' '4.5' 'String' 'True']


In [59]:
## Views and copy
a = np.array([1,2,3,4])
b = a     # Create views not a new array in memory
print(a, b)
a[0] = 10
print(a, b)     # Omg both 0 values are changed

# Lets check the memory address
print(id(a), id(b))    # Both are same

c = a.view()       # Address is changed but this memory address is pointing to same memory address
print(c)
print(id(c))

c[2] = 20
print(a, b, c)    # All changed

d =  a.copy()   # Brand new memory numpy object
print(id(a), id(d))
print(a, d)
d[3] = 40
print(a, d)   # Only changed in d not in a

[1 2 3 4] [1 2 3 4]
[10  2  3  4] [10  2  3  4]
2435282472432 2435282472432
[10  2  3  4]
2435282470192
[10  2 20  4] [10  2 20  4] [10  2 20  4]
2435282472432 2435282416864
[10  2 20  4] [10  2 20  4]
[10  2 20  4] [10  2 20 40]


In [60]:
# Reshape
a = np.arange(10, 19)
print(a)
b = a.reshape(3,3)
print(b)

# Append at the end of row three in b array
b = np.append(b , [[19, 20, 30]], axis = 0)
print(b)
b = np.append(b , [[100], [100], [100], [100]], axis = 1)
print(b)

[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 30]]
[[ 10  11  12 100]
 [ 13  14  15 100]
 [ 16  17  18 100]
 [ 19  20  30 100]]


In [61]:
# Append
np.append(a, [19, 20])   # It will not change
print(a)

[10 11 12 13 14 15 16 17 18]


In [62]:
# Insert
a = np.arange(10, 19)
print(a)
print(np.insert(a, 1, 200))

[10 11 12 13 14 15 16 17 18]
[ 10 200  11  12  13  14  15  16  17  18]


In [63]:
b = a.reshape(3,3)
# insert new row
print(np.insert(b, 1, -100, axis = 0))    # New row
print(np.insert(b, 1, -100, axis = 1))    # New column

[[  10   11   12]
 [-100 -100 -100]
 [  13   14   15]
 [  16   17   18]]
[[  10 -100   11   12]
 [  13 -100   14   15]
 [  16 -100   17   18]]


In [64]:
# Delete
a = np.arange(10, 19)
print(a)
print(np.delete(a, 2))

a = np.arange(10, 19)
print(a)
b = a.reshape(3,3)
print(b)
print(np.delete(b, 1, axis = 0))

[10 11 12 13 14 15 16 17 18]
[10 11 13 14 15 16 17 18]
[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [16 17 18]]


In [65]:
## nditer
sam = np.arange(0,10)
for x in np.nditer(sam):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [66]:
## ndenumerate
sam = np.arange(0,10)
for idx, x in np.ndenumerate(sam):
    print(idx, x)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9


In [67]:
# Split
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [68]:
print(np.split(a, 2))
first_arr = np.split(a, 2)[0]
second_arr = np.split(a, 2)[1]
print(first_arr)
print(second_arr)

print(np.split(a, 2, axis = 1))
first_arr = np.split(a, 2, axis = 1)[0]
second_arr = np.split(a, 2, axis = 1)[1]
print(first_arr)
print(second_arr)

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [69]:
# Concatinate
a = np.arange(24).reshape(4,6)
print(a)
b = np.arange(24).reshape(4,6)
print(b)
print(np.concatenate((a,b)))   # axis = 0
print(np.concatenate((a,b), axis = 1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]
 [12 13 14 15 16 17 12 13 14 15 16 17]
 [18 19 20 21 22 23 18 19 20 21 22 23]]


In [70]:
# tile
# what is difference between repeat and tile
a = np.arange(5)
print(np.tile(a, 3))

[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [71]:
a = np.arange(8).reshape(2,4)
print(np.tile(a, 2))
print(np.tile(a, (2,1)))   # 2 rows 1 column
print(np.tile(a, (2,2)))   # 2 rows 2 column

[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]
 [0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


In [72]:
# Repeat
# Here every element get replicated
a = np.arange(5)
print(np.repeat(a, 2))

a = np.arange(8).reshape(2,4)
print(np.repeat(a, 2, axis = 0))
print(np.repeat(a, 2, axis = 1))

[0 0 1 1 2 2 3 3 4 4]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]
 [4 5 6 7]]
[[0 0 1 1 2 2 3 3]
 [4 4 5 5 6 6 7 7]]
